[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Light" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Light Italic" }
