[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
#decorations = "none"
opacity = 0.97
option_as_alt = "Both"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
